Repository PonomarevDA/dronecan_application, pull requests merged in 2024-09, with the labels that each got.

#42 ArmingStatus
  include/serialization/subscriber.hpp
  include/serialization/uavcan/equipment/safety/ArmingStatus.h
Labels: enhancement

#43 moved logger from mini node to dronecan
  CMakeLists.txt
  include/serialization/logger.hpp
  include/serialization/logging.h
  src/logger.cpp
Labels: enhancement

#44 fix logger
  include/serialization/logging.h
  src/logger.cpp
Labels: bug

#45 refactor platform specific functions and restart request
  README.md
  examples/stm32_hal/hal.cpp
  examples/ubuntu/main.cpp
  include/application/dronecan_application_internal.h
  include/serialization/publisher.hpp
  src/dronecan.c
  src/weak.c
Labels: enhancement, clean up
